"""
Django settings for godi_ph_api project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import django

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7hz!gyaul#jp4b+5oody&=5dae8o0c7oknjz-b7*5og9qvez13'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#  配置跨域
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'config',
    'static',
    'demo',
    'django_crontab',
    'dynamic',
    'anomaly_analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 默认
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'godi_ph_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'godi_ph_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases


# product
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'check_system',
#         'USER': 'jeffreytian',
#         'PASSWORD': 'jeffreytian123',
#         'HOST': '100.115.82.51',
#         'PORT': '4321'
#     },
#     'cache_db': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cache_db',
#         'USER': 'jeffreytian',
#         'PASSWORD': 'jeffreytian123',
#         'HOST': '100.115.82.51',
#         'PORT': '4321'
#     }
# }

# dev
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'check_system',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '192.168.1.11',
        'PORT': '3306'
    },
    'cache_db': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cache_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '192.168.1.11',
        'PORT': '3306'
    }
}
DATABASE_ROUTERS = ['utils.DBRouter.DBRouter']

DATABASE_APPS_MAPPING = {
    'static': 'default',
    'dynamic': 'cache_db',
    'config': 'cache_db',
    'anomaly_analysis': 'cache_db',
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

## 跨域访问
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = (
#     '*',
# )
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

CRONJOBS = (
    ('0 8 * * * ', 'config.crontab.schedule.get_all_module', '>>/data/godizhang/DevOpsOa/godi_ph/backend/schedule.log '),
    ('0 8 * * * ', 'static.crontab.schedule.get_static_data', '>>/data/godizhang/DevOpsOa/godi_ph/backend/schedule.log '),
    ('0 8 * * * ', 'dynamic.crontab.schedule.get_dynamic_data', '>>/data/godizhang/DevOpsOa/godi_ph/backend/schedule.log '),
    ('0 8 * * * ', 'dynamic.crontab.schedule.get_monthly_avg_data', '>>/data/godizhang/DevOpsOa/godi_ph/backend/schedule.log '),
    ('0 8 * * * ', 'anomaly_analysis.crontab.schedule.count_anomaly_analysis', '>>/data/godizhang/DevOpsOa/godi_ph/backend/schedule.log '),
)
# redis配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://192.168.1.11:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # "PASSWORD": "godizhang"
        }
    }
}
# REDIS_TIMEOUT = 7 * 24 * 60 * 60
# CUBES_REDIS_TIMEOUT = 60 * 60
# NEVER_REDIS_TIMEOUT = 365 * 24 * 60 * 60
